version: 0.0
os: linux
files:
  - source: /
    destination: $HOME/

hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 180
      runas: root
  BeforeInstall:
    - location: setup_apache.sh
      timeout: 300
      runas: root
  Install:
    - location: setupdll.sh
      timeout: 300
      runas: root
  After Install:
    - location: setup_config.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 180
