version: 0.2

phases:
  install:
    commands:
      - sudo curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
      - sudo curl -sSL -O https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - sudo rm packages-microsoft-prod.deb
      - sudo apt-get update -y
      - sudo apt install zip -y
      - sudo apt install dotnet-sdk-5.0 -y
      - sudo dotnet add package Newtonsoft.Json --version 13.0.1
      - sudo mkdir $HOME/url-monitor

  build:
    commands:
      - echo Building the urlmonitor project on 'date'
      - sudo dotnet build *.csproj --runtime linux-x64   
      
  post_build:
    commands:
     - echo Build completed for urlmonitor project on 'date'
     - echo project publish started for urlmonitor project on 'date'
     - sudo dotnet publish *.sln --configuration Release --framework netcoreapp3.1 --runtime linux-x64 --output $HOME/url-monitor
     - sudo zip -r $HOME/url-monitor/url-monitor.zip $HOME/url-monitor/
artifacts:
  files:
     - $HOME/url-monitor/*.zip
     - appspec.yml
     - deployment_script/*
  discard-paths: yes
